'use server';
/**
 * @fileOverview A Genkit flow for generating unique quotes.
 *
 * - generateQuote - A function that generates a new quote.
 * - GenerateQuoteInput - The input type for the generateQuote function.
 * - GenerateQuoteOutput - The return type for the generateQuote function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateQuoteInputSchema = z.object({
  category: z.string().optional().describe('The category of the quote to generate (e.g., Motivational, Love).'),
});
export type GenerateQuoteInput = z.infer<typeof GenerateQuoteInputSchema>;

const GenerateQuoteOutputSchema = z.object({
  quote: z.string().describe('The generated quote.'),
  author: z.string().describe('The author of the quote. This can be a real person or a creative pseudonym if generated by AI.'),
  category: z.string().describe('The category of the generated quote.'),
});
export type GenerateQuoteOutput = z.infer<typeof GenerateQuoteOutputSchema>;

export async function generateQuote(input: GenerateQuoteInput): Promise<GenerateQuoteOutput> {
  return generateQuoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateQuotePrompt',
  input: { schema: GenerateQuoteInputSchema },
  output: { schema: GenerateQuoteOutputSchema },
  prompt: `You are an AI that specializes in creating new, insightful, and meaningful quotes.
  Generate a single, unique quote based on the following category: {{{category}}}.
  If the category is "Any" or not provided, you can choose any inspirational category.
  The quote should be original. Assign a creative or fitting author name to the quote.
  `,
});

const generateQuoteFlow = ai.defineFlow(
  {
    name: 'generateQuoteFlow',
    inputSchema: GenerateQuoteInputSchema,
    outputSchema: GenerateQuoteOutputSchema,
  },
  async input => {
    const { output } = await prompt(input);
    return output!;
  }
);
