'use server';
/**
 * @fileOverview A Genkit flow for generating unique quotes.
 *
 * - generateQuote - A function that generates a new quote.
 * - GenerateQuoteInput - The input type for the generateQuote function.
 * - GenerateQuoteOutput - The return type for the generateQuote function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateQuoteInputSchema = z.object({
  category: z.string().optional().describe('The category of the quote to generate (e.g., Motivational, Love).'),
});
export type GenerateQuoteInput = z.infer<typeof GenerateQuoteInputSchema>;

const QuoteSchema = z.object({
  quote: z.string().describe('The generated quote.'),
  author: z.string().describe('The author of the quote. This can be a real person or a creative pseudonym if generated by AI.'),
  category: z.string().describe('The category of the generated quote.'),
});

const GenerateQuoteOutputSchema = z.object({
  quotes: z.array(QuoteSchema).describe('An array of 20 generated quotes.'),
});
export type GenerateQuoteOutput = z.infer<typeof GenerateQuoteOutputSchema>;


export async function generateQuote(input: GenerateQuoteInput): Promise<GenerateQuoteOutput> {
  return generateQuoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateQuotePrompt',
  input: { schema: GenerateQuoteInputSchema },
  output: { schema: GenerateQuoteOutputSchema },
  prompt: `You are a creative and insightful AI, specializing in crafting original and thought-provoking quotes. Your tone is professional and inspiring.

Generate 20 unique and meaningful quotes based on the following category: {{{category}}}.

If the category is "Any" or not provided, choose any inspirational category. The quotes must be original and not simple clichés. Assign a fitting author to each quote; this can be a creative pseudonym or simply "AI".`,
});

const generateQuoteFlow = ai.defineFlow(
  {
    name: 'generateQuoteFlow',
    inputSchema: GenerateQuoteInputSchema,
    outputSchema: GenerateQuoteOutputSchema,
  },
  async input => {
    const { output } = await prompt(input);
    return output!;
  }
);
